# -*- coding: utf-8 -*-
"""Hiba.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Ax-KXQ5duG_WEVRQ2qZB5YdXwNZWqXs

Would you say that any of the three networks was randomly generated? Why? If not what type of network are they then? What may that imply with respect to the law firm, the way they work, the way people behave or relate to each other?
"""

install.packages(c('igraph','ggplot2','ggraph'))

library(igraph)
library(ggplot2)
library(ggraph)

install.packages('networkx')

advice <- read_graph("advice.gml", format = "gml")
friend <- read_graph("friend.gml", format = "gml")
learn_advice <- read_graph("learn_advice.gml", format = "gml")
work <- read_graph("work.gml", format = "gml")

"""Analyzing the three networks"""

calculate_properties = function(network) {
  return(list(
    number_of_nodes = vcount(network),
    number_of_edges = ecount(network),
    average_degree = mean(degree(network)),
    clustering_coefficient = transitivity(network, type = "average"),
    average_path_length = average.path.length(network),
    diameter = diameter(network),
    density = edge_density(network)
  ))
}

advice_properties <- calculate_properties(advice)
friend_properties <- calculate_properties(friend)
work_properties <- calculate_properties(work)

print("Advice Network Properties:")
print(advice_properties)

print("Friend Network Properties:")
print(friend_properties)

print("Work Network Properties:")
print(work_properties)

"""**Number of Nodes**: All three networks have the same number of nodes (71), which likely represents the number of individuals in the law firm.

Number of Edges and Average Degree:

**Advice Network**: Has the highest number of edges (892) and average degree (25.13). This suggests that seeking advice is a common practice, with many individuals consulting each other.
Friend Network: Has fewer edges (575) and a lower average degree (16.20) compared to the Advice Network. This indicates more selective relationships in terms of friendships.
**Work Network**: Falls between the other two networks in terms of edges (756) and average degree (21.30), suggesting a significant level of collaboration or work-related interactions among individuals.
Clustering Coefficient:

**High in Advice and Friend Networks**: The clustering coefficients for the Advice (0.52) and Friend (0.51) networks are relatively high, indicating a tendency to form tight-knit groups. In the context of a law firm, this might reflect strong departmental or practice area cliques or teams.
**Lower in Work Network**: The Work network has a lower clustering coefficient (0.39), which might suggest a more distributed or hierarchical structure in professional interactions, where work relationships are not as tightly knit.
Average Path Length and Diameter:

**Small World Properties**: All networks have relatively short average path lengths (ranging from 2.10 to 2.51) and small diameters (4 to 7). This indicates small-world properties, where most individuals are separated by only a few steps, facilitating efficient information flow and collaboration.
Density:

The densities of the networks range from 0.12 to 0.18, with the Advice network being the densest. This suggests that, while there are many connections, the networks are not fully connected, which is typical in real-world networks.

**Would you say that any of the three networks was randomly generated? Why? If not what type of network are they then? What may that imply with respect to the law firm, the way they work, the way people behave or relate to each other?**

The three networks are unlikely to be randomly Generated: None of the networks appear to be randomly generated. This conclusion is based on several key observations:
**High Clustering Coefficients**: All three networks have relatively high clustering coefficients (especially the Advice and Friend networks). Random networks typically exhibit low clustering coefficients because connections in random networks are not likely to be transitive (i.e., friends of friends are not necessarily friends).
**Small-World Properties**: The short average path lengths and small diameters observed in all three networks are characteristic of small-world networks, which are not random. Random networks do have short path lengths but usually lack the high clustering seen here.
Average Degree and Density: The average degrees and densities of these networks, along with the pattern of connections (indicated by the clustering coefficients and path lengths), suggest a more structured and intentional pattern of relationships than what would be expected in a random network.
# Type of Networks
**Small-World Networks**: All three networks display characteristics of small-world networks — high clustering coefficients combined with short average path lengths. This suggests a structure where individuals are highly interconnected within certain groups or clusters, but still maintain relatively short paths across the entire network.
**Social and Professional Networks**: These networks represent social (Friend), advisory (Advice), and professional (Work) relationships within the firm, each with its distinct structure and dynamics.
Implications for the Law Firm
**Efficient Communication and Collaboration**: The small-world nature suggests efficient communication paths throughout the firm. Information can quickly travel due to the short path lengths, aiding in effective collaboration and decision-making.
**Influence of Social Structures**: The distinct characteristics of the Friend network suggest that social relationships might play a significant role in the firm's dynamics, potentially influencing work-related decisions and collaborations.
**Clustered Groups or Teams**: High clustering, especially in the Advice and Friend networks, implies the presence of closely-knit groups or teams. This could be beneficial for teamwork and support but might also lead to silos within the organization.
**Knowledge and Advice Sharing**: The structure of the Advice network indicates a culture of seeking and sharing advice, which is a positive trait for knowledge dissemination and mentorship within the firm.
"""
